// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erdvwvtuqujlvaluwxol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyZHZ3dnR1cXVqbHZhbHV3eG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzU1MDAsImV4cCI6MjA2MzUxMTUwMH0.OtRx5pcSTTx3YRZeGDuEHM7xF1SrY40xytrdDeP6H7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);